//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagedUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManagedUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap application {
            get {
                object obj = ResourceManager.GetObject("application", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap application_side_tree {
            get {
                object obj = ResourceManager.GetObject("application_side_tree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap application_view_tile {
            get {
                object obj = ResourceManager.GetObject("application_view_tile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap book_open {
            get {
                object obj = ResourceManager.GetObject("book_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bullet_black {
            get {
                object obj = ResourceManager.GetObject("bullet_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bullet_white {
            get {
                object obj = ResourceManager.GetObject("bullet_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Abort.
        /// </summary>
        internal static string Button_Abort {
            get {
                return ResourceManager.GetString("Button_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Don&apos;t save.
        /// </summary>
        internal static string Button_DontSave {
            get {
                return ResourceManager.GetString("Button_DontSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ignore.
        /// </summary>
        internal static string Button_Ignore {
            get {
                return ResourceManager.GetString("Button_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;No.
        /// </summary>
        internal static string Button_NO {
            get {
                return ResourceManager.GetString("Button_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Retry.
        /// </summary>
        internal static string Button_Retry {
            get {
                return ResourceManager.GetString("Button_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Yes.
        /// </summary>
        internal static string Button_Yes {
            get {
                return ResourceManager.GetString("Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviroment.
        /// </summary>
        internal static string Category_Enviroment {
            get {
                return ResourceManager.GetString("Category_Enviroment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank Combobox.
        /// </summary>
        internal static string CBMI_Name_Blank {
            get {
                return ResourceManager.GetString("CBMI_Name_Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank Combobox for testing purpose.
        /// </summary>
        internal static string CBMI_Tooltip_Blank {
            get {
                return ResourceManager.GetString("CBMI_Tooltip_Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit &amp;Menu.
        /// </summary>
        internal static string CMI_Name_EditMenuItems {
            get {
                return ResourceManager.GetString("CMI_Name_EditMenuItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit shortcuts (hotkeys).
        /// </summary>
        internal static string CMI_Name_EditShortcuts {
            get {
                return ResourceManager.GetString("CMI_Name_EditShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit &amp;Theme.
        /// </summary>
        internal static string CMI_Name_EditTheme {
            get {
                return ResourceManager.GetString("CMI_Name_EditTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit &amp;Toolbars.
        /// </summary>
        internal static string CMI_Name_EditToolbars {
            get {
                return ResourceManager.GetString("CMI_Name_EditToolbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Exit.
        /// </summary>
        internal static string CMI_Name_Exit {
            get {
                return ResourceManager.GetString("CMI_Name_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;Help.
        /// </summary>
        internal static string CMI_Name_Help {
            get {
                return ResourceManager.GetString("CMI_Name_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load La&amp;yout.
        /// </summary>
        internal static string CMI_Name_LoadLayout {
            get {
                return ResourceManager.GetString("CMI_Name_LoadLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Theme.
        /// </summary>
        internal static string CMI_Name_LoadTheme {
            get {
                return ResourceManager.GetString("CMI_Name_LoadTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Layout As.
        /// </summary>
        internal static string CMI_Name_SaveLayout {
            get {
                return ResourceManager.GetString("CMI_Name_SaveLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Co&amp;nsole.
        /// </summary>
        internal static string CMI_Name_ShowConsole {
            get {
                return ResourceManager.GetString("CMI_Name_ShowConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;Services.
        /// </summary>
        internal static string CMI_Name_ShowServices {
            get {
                return ResourceManager.GetString("CMI_Name_ShowServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Settings.
        /// </summary>
        internal static string CMI_Name_ShowSettings {
            get {
                return ResourceManager.GetString("CMI_Name_ShowSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit menu items map, this allows to customize the menu items of the application..
        /// </summary>
        internal static string CMI_Tooltip_EditMenuItems {
            get {
                return ResourceManager.GetString("CMI_Tooltip_EditMenuItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit shortcuts and hotkeys for the menu items and the commands of the application.
        /// </summary>
        internal static string CMI_Tooltip_EditShortcuts {
            get {
                return ResourceManager.GetString("CMI_Tooltip_EditShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit theme and change the way the application look like..
        /// </summary>
        internal static string CMI_Tooltip_EditTheme {
            get {
                return ResourceManager.GetString("CMI_Tooltip_EditTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the toolbars, this allows to customize toolbars and buttons in the toolbars..
        /// </summary>
        internal static string CMI_Tooltip_EditToolbars {
            get {
                return ResourceManager.GetString("CMI_Tooltip_EditToolbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the application.
        /// </summary>
        internal static string CMI_Tooltip_Exit {
            get {
                return ResourceManager.GetString("CMI_Tooltip_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show help about using the applciation..
        /// </summary>
        internal static string CMI_Tooltip_Help {
            get {
                return ResourceManager.GetString("CMI_Tooltip_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load controls layout from a file.
        /// </summary>
        internal static string CMI_Tooltip_LoadLayout {
            get {
                return ResourceManager.GetString("CMI_Tooltip_LoadLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current controls layout into a file.
        /// </summary>
        internal static string CMI_Tooltip_SaveLayout {
            get {
                return ResourceManager.GetString("CMI_Tooltip_SaveLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show MangedUI internal console that allows to enter commands manually..
        /// </summary>
        internal static string CMI_Tooltip_ShowConsole {
            get {
                return ResourceManager.GetString("CMI_Tooltip_ShowConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all services that currently are running.
        /// </summary>
        internal static string CMI_Tooltip_ShowServices {
            get {
                return ResourceManager.GetString("CMI_Tooltip_ShowServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the settings of the application..
        /// </summary>
        internal static string CMI_Tooltip_ShowSettings {
            get {
                return ResourceManager.GetString("CMI_Tooltip_ShowSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cross {
            get {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cross_black {
            get {
                object obj = ResourceManager.GetObject("cross_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Language.
        /// </summary>
        internal static string DMI_Name_Language {
            get {
                return ResourceManager.GetString("DMI_Name_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Layouts.
        /// </summary>
        internal static string DMI_Name_Layouts {
            get {
                return ResourceManager.GetString("DMI_Name_Layouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;hortcut Maps.
        /// </summary>
        internal static string DMI_Name_Shortcuts {
            get {
                return ResourceManager.GetString("DMI_Name_Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabs.
        /// </summary>
        internal static string DMI_Name_Tabs {
            get {
                return ResourceManager.GetString("DMI_Name_Tabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Themes.
        /// </summary>
        internal static string DMI_Name_Themes {
            get {
                return ResourceManager.GetString("DMI_Name_Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Toolbars.
        /// </summary>
        internal static string DMI_Name_Toolbars {
            get {
                return ResourceManager.GetString("DMI_Name_Toolbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core cannot initialize..
        /// </summary>
        internal static string Error_CoreCannotInitialize {
            get {
                return ResourceManager.GetString("Error_CoreCannotInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required service list is not valid in parameters, application cannot be initialized..
        /// </summary>
        internal static string Error_NotValidRequiredServicesList {
            get {
                return ResourceManager.GetString("Error_NotValidRequiredServicesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required service list is empty, at least one service must be listed in order of the application to work. Application cannot be initialized..
        /// </summary>
        internal static string Error_NotValidRequiredServicesListAtLeastOneService {
            get {
                return ResourceManager.GetString("Error_NotValidRequiredServicesListAtLeastOneService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a missing required service in the application. Application cannot be initialized..
        /// </summary>
        internal static string Error_NotValidRequiredServicesListAtMissingService {
            get {
                return ResourceManager.GetString("Error_NotValidRequiredServicesListAtMissingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTF Document (*.rtf)|*.rtf;|Text file (*.txt)|*.txt;|All files (*.*)|*.*.
        /// </summary>
        internal static string Filter_TextFiles {
            get {
                return ResourceManager.GetString("Filter_TextFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout file.
        /// </summary>
        internal static string FilterName_ControlsLayout {
            get {
                return ResourceManager.GetString("FilterName_ControlsLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Items Map file.
        /// </summary>
        internal static string FilterName_MenuItemsMapFile {
            get {
                return ResourceManager.GetString("FilterName_MenuItemsMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Backup.
        /// </summary>
        internal static string FilterName_SettingsBackup {
            get {
                return ResourceManager.GetString("FilterName_SettingsBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts Map file.
        /// </summary>
        internal static string FilterName_ShortcutsMapFile {
            get {
                return ResourceManager.GetString("FilterName_ShortcutsMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme file.
        /// </summary>
        internal static string FilterName_ThemeFile {
            get {
                return ResourceManager.GetString("FilterName_ThemeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbars Map file.
        /// </summary>
        internal static string FilterName_ToolbarsMapFile {
            get {
                return ResourceManager.GetString("FilterName_ToolbarsMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Exit {
            get {
                object obj = ResourceManager.GetObject("Icon_Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Help {
            get {
                object obj = ResourceManager.GetObject("Icon_Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Wrench {
            get {
                object obj = ResourceManager.GetObject("Icon_Wrench", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keyboard {
            get {
                object obj = ResourceManager.GetObject("keyboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Label_Version {
            get {
                return ResourceManager.GetString("Label_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered shortcut (hotkey) is already taken by other menu item or command..
        /// </summary>
        internal static string Message_EnteredHotkeyIsAlreadTaken {
            get {
                return ResourceManager.GetString("Message_EnteredHotkeyIsAlreadTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting settings requires to save all settings first, continue ?.
        /// </summary>
        internal static string Message_ExportSettingsRequiresSaveSettings {
            get {
                return ResourceManager.GetString("Message_ExportSettingsRequiresSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Items Map saved successfully..
        /// </summary>
        internal static string Message_MenuItemsMapSavedSuccessfully {
            get {
                return ResourceManager.GetString("Message_MenuItemsMapSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an item first !!.
        /// </summary>
        internal static string Message_PleaseSelectAnItemFirst {
            get {
                return ResourceManager.GetString("Message_PleaseSelectAnItemFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the menu items file !!.
        /// </summary>
        internal static string Message_PleaseSpecifyTheMIRFile {
            get {
                return ResourceManager.GetString("Message_PleaseSpecifyTheMIRFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the shortcuts file !.
        /// </summary>
        internal static string Message_PleaseSpecifyTheShortcutsFile {
            get {
                return ResourceManager.GetString("Message_PleaseSpecifyTheShortcutsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the theme file !!.
        /// </summary>
        internal static string Message_PleaseSpecifyTheThemeFile {
            get {
                return ResourceManager.GetString("Message_PleaseSpecifyTheThemeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the application to apply..
        /// </summary>
        internal static string Message_RestartToApply {
            get {
                return ResourceManager.GetString("Message_RestartToApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings exported successfully..
        /// </summary>
        internal static string Message_SettingsExportedSuccessfully {
            get {
                return ResourceManager.GetString("Message_SettingsExportedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings imported successfully..
        /// </summary>
        internal static string Message_SettingsImportedSuccessfully {
            get {
                return ResourceManager.GetString("Message_SettingsImportedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts Map saved successfully..
        /// </summary>
        internal static string Message_ShortcutsMapSavedSuccessfully {
            get {
                return ResourceManager.GetString("Message_ShortcutsMapSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitter cannot have subitems..
        /// </summary>
        internal static string Message_SplitterCannotHaveSubitems {
            get {
                return ResourceManager.GetString("Message_SplitterCannotHaveSubitems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no menu item to save !!.
        /// </summary>
        internal static string Message_ThereIsNoMenuItemToSave {
            get {
                return ResourceManager.GetString("Message_ThereIsNoMenuItemToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbars Map saved successfully..
        /// </summary>
        internal static string Message_ToolbarsMapSavedSuccessfully {
            get {
                return ResourceManager.GetString("Message_ToolbarsMapSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to export the settings !!.
        /// </summary>
        internal static string Message_UnableToExportTheSettings {
            get {
                return ResourceManager.GetString("Message_UnableToExportTheSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to import the settings !!.
        /// </summary>
        internal static string Message_UnableToImportTheSettings {
            get {
                return ResourceManager.GetString("Message_UnableToImportTheSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the current menu items map file !!.
        /// </summary>
        internal static string Message_UnableToLoadCurrentMIRFile {
            get {
                return ResourceManager.GetString("Message_UnableToLoadCurrentMIRFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the current shortcuts map file !!.
        /// </summary>
        internal static string Message_UnableToLoadCurrentShrtMapFile {
            get {
                return ResourceManager.GetString("Message_UnableToLoadCurrentShrtMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the current theme !.
        /// </summary>
        internal static string Message_UnableToLoadCurrentTheme {
            get {
                return ResourceManager.GetString("Message_UnableToLoadCurrentTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the menu items map file at.
        /// </summary>
        internal static string Message_UnableToLoadMIRFileAt {
            get {
                return ResourceManager.GetString("Message_UnableToLoadMIRFileAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the current toolbars map file !!.
        /// </summary>
        internal static string Message_UnableToLoadTheCurrentTBRFile {
            get {
                return ResourceManager.GetString("Message_UnableToLoadTheCurrentTBRFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the shortcuts map file at.
        /// </summary>
        internal static string Message_UnableToLoadTheShortcutsMapFileAt {
            get {
                return ResourceManager.GetString("Message_UnableToLoadTheShortcutsMapFileAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the toolbars map file at.
        /// </summary>
        internal static string Message_UnableToLoadTheTBRMapFileAt {
            get {
                return ResourceManager.GetString("Message_UnableToLoadTheTBRMapFileAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save the map file !!.
        /// </summary>
        internal static string Message_UnableToSaveTheMapFile {
            get {
                return ResourceManager.GetString("Message_UnableToSaveTheMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save the theme file.
        /// </summary>
        internal static string Message_UnableToSaveTheThemeFile {
            get {
                return ResourceManager.GetString("Message_UnableToSaveTheThemeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Initialize.
        /// </summary>
        internal static string MessageCaption_CoreInitialize {
            get {
                return ResourceManager.GetString("MessageCaption_CoreInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MessageIcon_Error {
            get {
                object obj = ResourceManager.GetObject("MessageIcon_Error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MessageIcon_Info {
            get {
                object obj = ResourceManager.GetObject("MessageIcon_Info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MessageIcon_Question {
            get {
                object obj = ResourceManager.GetObject("MessageIcon_Question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MessageIcon_Save {
            get {
                object obj = ResourceManager.GetObject("MessageIcon_Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MessageIcon_Stop {
            get {
                object obj = ResourceManager.GetObject("MessageIcon_Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MessageIcon_Warning {
            get {
                object obj = ResourceManager.GetObject("MessageIcon_Warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string MIR_Name_Edit {
            get {
                return ResourceManager.GetString("MIR_Name_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string MIR_Name_File {
            get {
                return ResourceManager.GetString("MIR_Name_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string MIR_Name_Help {
            get {
                return ResourceManager.GetString("MIR_Name_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        internal static string MIR_Name_Tools {
            get {
                return ResourceManager.GetString("MIR_Name_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View.
        /// </summary>
        internal static string MIR_Name_View {
            get {
                return ResourceManager.GetString("MIR_Name_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to edit hotkeys (shortcuts) for the application..
        /// </summary>
        internal static string SC_Description_Hotkeys {
            get {
                return ResourceManager.GetString("SC_Description_Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to edit the main menu items of the application..
        /// </summary>
        internal static string SC_Description_MenuItems {
            get {
                return ResourceManager.GetString("SC_Description_MenuItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to edit the theme of the application..
        /// </summary>
        internal static string SC_Description_Theme {
            get {
                return ResourceManager.GetString("SC_Description_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys (shortcuts).
        /// </summary>
        internal static string SC_Name_Hotkeys {
            get {
                return ResourceManager.GetString("SC_Name_Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Items.
        /// </summary>
        internal static string SC_Name_MenuItems {
            get {
                return ResourceManager.GetString("SC_Name_MenuItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string SC_Name_Theme {
            get {
                return ResourceManager.GetString("SC_Name_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All service(s) closed..
        /// </summary>
        internal static string Status_AllServicesClosed {
            get {
                return ResourceManager.GetString("Status_AllServicesClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already blacklisted..
        /// </summary>
        internal static string Status_AlreadyBlacklisted {
            get {
                return ResourceManager.GetString("Status_AlreadyBlacklisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already enabled..
        /// </summary>
        internal static string Status_AlreadyEnabled {
            get {
                return ResourceManager.GetString("Status_AlreadyEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application folders checked successfully..
        /// </summary>
        internal static string Status_ApplicationFoldersCheckedSuccessfully {
            get {
                return ResourceManager.GetString("Status_ApplicationFoldersCheckedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying menu items map to the main window.
        /// </summary>
        internal static string Status_ApplyingMenuItemsMapToTheMainWindow {
            get {
                return ResourceManager.GetString("Status_ApplyingMenuItemsMapToTheMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying toolbars map to the main window.
        /// </summary>
        internal static string Status_ApplyingToolbarsMapToTheMainWindow {
            get {
                return ResourceManager.GetString("Status_ApplyingToolbarsMapToTheMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attembting to execute an empty shortcut..
        /// </summary>
        internal static string Status_AttembtingToExecuteAnEmptyShortcut {
            get {
                return ResourceManager.GetString("Status_AttembtingToExecuteAnEmptyShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot be disabled because of this service is marked as a DEFAULT service..
        /// </summary>
        internal static string Status_CannotBeBlacklistedDefaultService {
            get {
                return ResourceManager.GetString("Status_CannotBeBlacklistedDefaultService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot be enabled, the service does not exist..
        /// </summary>
        internal static string Status_CannotBeEnabledServiceDoesntExist {
            get {
                return ResourceManager.GetString("Status_CannotBeEnabledServiceDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot be enabled, the service is marked as a DEFAULT service (default services cannot be disabled, did you hack blacklist ?)..
        /// </summary>
        internal static string Status_CannotBeEnabledTheServiceIsDefault {
            get {
                return ResourceManager.GetString("Status_CannotBeEnabledTheServiceIsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking application folders ....
        /// </summary>
        internal static string Status_CheckingApplicationFolders {
            get {
                return ResourceManager.GetString("Status_CheckingApplicationFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing services ....
        /// </summary>
        internal static string Status_ClosingServices {
            get {
                return ResourceManager.GetString("Status_ClosingServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The core is initialized successfully..
        /// </summary>
        internal static string Status_CoreIsInitialized {
            get {
                return ResourceManager.GetString("Status_CoreIsInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not exist, thus it cannot be disabled..
        /// </summary>
        internal static string Status_DoesntExistCannotBeDisabled {
            get {
                return ResourceManager.GetString("Status_DoesntExistCannotBeDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding.
        /// </summary>
        internal static string Status_ErrorAdding {
            get {
                return ResourceManager.GetString("Status_ErrorAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing close-up commands.
        /// </summary>
        internal static string Status_ExecutingCloseupCommands {
            get {
                return ResourceManager.GetString("Status_ExecutingCloseupCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing command.
        /// </summary>
        internal static string Status_ExecutingCommand {
            get {
                return ResourceManager.GetString("Status_ExecutingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing command combination.
        /// </summary>
        internal static string Status_ExecutingCommandCombination {
            get {
                return ResourceManager.GetString("Status_ExecutingCommandCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing command-lines.
        /// </summary>
        internal static string Status_ExecutingCommandLines {
            get {
                return ResourceManager.GetString("Status_ExecutingCommandLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing start-up commands.
        /// </summary>
        internal static string Status_ExecutingStartupCommands {
            get {
                return ResourceManager.GetString("Status_ExecutingStartupCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is damaged or not shortcuts map file.
        /// </summary>
        internal static string Status_FileIsDamagedOrNotAShrt {
            get {
                return ResourceManager.GetString("Status_FileIsDamagedOrNotAShrt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is damaged or not tab controls map file..
        /// </summary>
        internal static string Status_FileIsDamagedOrNotTCC {
            get {
                return ResourceManager.GetString("Status_FileIsDamagedOrNotTCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file is not exist at.
        /// </summary>
        internal static string Status_fileIsNotExistAt {
            get {
                return ResourceManager.GetString("Status_fileIsNotExistAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu items map set to default !!.
        /// </summary>
        internal static string Status_GUI1 {
            get {
                return ResourceManager.GetString("Status_GUI1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbars map set to default !!.
        /// </summary>
        internal static string Status_GUI2 {
            get {
                return ResourceManager.GetString("Status_GUI2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts map set to default !.
        /// </summary>
        internal static string Status_GUI3 {
            get {
                return ResourceManager.GetString("Status_GUI3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme has been set to default !!.
        /// </summary>
        internal static string Status_GUI4 {
            get {
                return ResourceManager.GetString("Status_GUI4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been blacklisted (disabled) successfully..
        /// </summary>
        internal static string Status_HasBeenBlacklisted {
            get {
                return ResourceManager.GetString("Status_HasBeenBlacklisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been removed from blacklist (enabled) successfully..
        /// </summary>
        internal static string Status_HasBeenRemovedFromBlacklist {
            get {
                return ResourceManager.GetString("Status_HasBeenRemovedFromBlacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i.e. service removed.
        /// </summary>
        internal static string Status_IEServiceRemoved {
            get {
                return ResourceManager.GetString("Status_IEServiceRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing the core ....
        /// </summary>
        internal static string Status_InitializingTheCore {
            get {
                return ResourceManager.GetString("Status_InitializingTheCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid parameter !!.
        /// </summary>
        internal static string Status_InvalidParameter {
            get {
                return ResourceManager.GetString("Status_InvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language id is not exist.
        /// </summary>
        internal static string Status_LanguageIdIsNotExist {
            get {
                return ResourceManager.GetString("Status_LanguageIdIsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language interface found..
        /// </summary>
        internal static string Status_LanguageInterfaceFound {
            get {
                return ResourceManager.GetString("Status_LanguageInterfaceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language interface set to.
        /// </summary>
        internal static string Status_LanguageInterfaceSetTo {
            get {
                return ResourceManager.GetString("Status_LanguageInterfaceSetTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading language interfeces ....
        /// </summary>
        internal static string Status_LoadingLanguageInterfeces {
            get {
                return ResourceManager.GetString("Status_LoadingLanguageInterfeces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading menu items map at.
        /// </summary>
        internal static string Status_LoadingMenuItemsMapAt {
            get {
                return ResourceManager.GetString("Status_LoadingMenuItemsMapAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading services .....
        /// </summary>
        internal static string Status_LoadingServices {
            get {
                return ResourceManager.GetString("Status_LoadingServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading settings ....
        /// </summary>
        internal static string Status_LoadingSettings {
            get {
                return ResourceManager.GetString("Status_LoadingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading shortcuts map at.
        /// </summary>
        internal static string Status_LoadingShortcutsMapAt {
            get {
                return ResourceManager.GetString("Status_LoadingShortcutsMapAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading toolbar representators map at.
        /// </summary>
        internal static string Status_LoadingTBRMapFile {
            get {
                return ResourceManager.GetString("Status_LoadingTBRMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading tab controls map.
        /// </summary>
        internal static string Status_LoadingTCCMap {
            get {
                return ResourceManager.GetString("Status_LoadingTCCMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading the main window ....
        /// </summary>
        internal static string Status_LoadingTheMainWindow {
            get {
                return ResourceManager.GetString("Status_LoadingTheMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading the theme file at.
        /// </summary>
        internal static string Status_LoadingTheThemeFileAt {
            get {
                return ResourceManager.GetString("Status_LoadingTheThemeFileAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main window loaded successfully..
        /// </summary>
        internal static string Status_MainWindowLoadedSuccessfully {
            get {
                return ResourceManager.GetString("Status_MainWindowLoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu items map loaded successfully from path.
        /// </summary>
        internal static string Status_MenuItemsMapLoadedSuccessfullyFromPath {
            get {
                return ResourceManager.GetString("Status_MenuItemsMapLoadedSuccessfullyFromPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu items map saved successfully at path.
        /// </summary>
        internal static string Status_MenuItemsMapSavedSuccessfullyAtPath {
            get {
                return ResourceManager.GetString("Status_MenuItemsMapSavedSuccessfullyAtPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR !! Unable to load tooltip from resources using key.
        /// </summary>
        internal static string Status_MIEError4 {
            get {
                return ResourceManager.GetString("Status_MIEError4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: attempting to add children to smi in the menu items map!.
        /// </summary>
        internal static string Status_MIRError1 {
            get {
                return ResourceManager.GetString("Status_MIRError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: attempting to include root menu item in place that not root..
        /// </summary>
        internal static string Status_MIRError2 {
            get {
                return ResourceManager.GetString("Status_MIRError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding element of CMI: the element of the menu map is set as CMI but the menu item representator is not a CMI !!.
        /// </summary>
        internal static string Status_MIRError3 {
            get {
                return ResourceManager.GetString("Status_MIRError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu items map applyed successfully..
        /// </summary>
        internal static string Status_MIRMapApplyed {
            get {
                return ResourceManager.GetString("Status_MIRMapApplyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No language interface found. Using default interface &apos;en-US&apos;.
        /// </summary>
        internal static string Status_NoLanguageInterfaceFound {
            get {
                return ResourceManager.GetString("Status_NoLanguageInterfaceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No menu items map loaded in the GUI Core !!.
        /// </summary>
        internal static string Status_NoMenuItemsMapLoadedtheGUICore {
            get {
                return ResourceManager.GetString("Status_NoMenuItemsMapLoadedtheGUICore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no parameter passed !.
        /// </summary>
        internal static string Status_NoParamPassed {
            get {
                return ResourceManager.GetString("Status_NoParamPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service is blacklisted !!.
        /// </summary>
        internal static string Status_NoServiceInBlacklist {
            get {
                return ResourceManager.GetString("Status_NoServiceInBlacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service is listed as blacklisted..
        /// </summary>
        internal static string Status_NoServiceIsListedAsBlacklisted {
            get {
                return ResourceManager.GetString("Status_NoServiceIsListedAsBlacklisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tab controls map loaded in the core..
        /// </summary>
        internal static string Status_NoTCCLoadedInCore {
            get {
                return ResourceManager.GetString("Status_NoTCCLoadedInCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No toolbars map loaded in the GUI Core !!.
        /// </summary>
        internal static string Status_NoToolbarsMapLoadedInTheGUICore {
            get {
                return ResourceManager.GetString("Status_NoToolbarsMapLoadedInTheGUICore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready !.
        /// </summary>
        internal static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving menu items map at path.
        /// </summary>
        internal static string Status_SavingMenuItemsMapAtPath {
            get {
                return ResourceManager.GetString("Status_SavingMenuItemsMapAtPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving the settings ......
        /// </summary>
        internal static string Status_SavingSettings {
            get {
                return ResourceManager.GetString("Status_SavingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving shortcuts map.
        /// </summary>
        internal static string Status_SavingShortcutsMap {
            get {
                return ResourceManager.GetString("Status_SavingShortcutsMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving toolbar representators map at path.
        /// </summary>
        internal static string Status_SavingTBRAt {
            get {
                return ResourceManager.GetString("Status_SavingTBRAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving tab controls map at.
        /// </summary>
        internal static string Status_SavingTCCAt {
            get {
                return ResourceManager.GetString("Status_SavingTCCAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving the theme file at.
        /// </summary>
        internal static string Status_SavingTHMFile {
            get {
                return ResourceManager.GetString("Status_SavingTHMFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service found.
        /// </summary>
        internal static string Status_ServiceFound {
            get {
                return ResourceManager.GetString("Status_ServiceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: this service id is in blacklist but the service cannot be found.
        /// </summary>
        internal static string Status_ServiceIDInBlackListCannotBeFound {
            get {
                return ResourceManager.GetString("Status_ServiceIDInBlackListCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service is blacklisted and successfully removed (not initialized)..
        /// </summary>
        internal static string Status_ServiceIsBlacklistedAndRemoved {
            get {
                return ResourceManager.GetString("Status_ServiceIsBlacklistedAndRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting language interface .....
        /// </summary>
        internal static string Status_SettingLanguageInterface {
            get {
                return ResourceManager.GetString("Status_SettingLanguageInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings loaded successfully..
        /// </summary>
        internal static string Status_SettingsLoadedSuccessfully {
            get {
                return ResourceManager.GetString("Status_SettingsLoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved successfully..
        /// </summary>
        internal static string Status_SettingsSavedSuccessfully {
            get {
                return ResourceManager.GetString("Status_SettingsSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts enabled for this tab control !.
        /// </summary>
        internal static string Status_ShortcutsEnabledForThisTabControl {
            get {
                return ResourceManager.GetString("Status_ShortcutsEnabledForThisTabControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts map file loaded successfully from path.
        /// </summary>
        internal static string Status_ShortcutsMapFileLoadedSuccessfullyFromPath {
            get {
                return ResourceManager.GetString("Status_ShortcutsMapFileLoadedSuccessfullyFromPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts map saved successfully.
        /// </summary>
        internal static string Status_ShortcutsMapSavedSuccessfully {
            get {
                return ResourceManager.GetString("Status_ShortcutsMapSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts suppressed for this tab control !.
        /// </summary>
        internal static string Status_ShortcutsSuppressedForThisTabControl {
            get {
                return ResourceManager.GetString("Status_ShortcutsSuppressedForThisTabControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toolbar is not exist.
        /// </summary>
        internal static string Status_TBRCannotBeFound {
            get {
                return ResourceManager.GetString("Status_TBRCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBR ERROR: Attembting to add DMI/RMI into a toolbar. Error in map..
        /// </summary>
        internal static string Status_TBRError1 {
            get {
                return ResourceManager.GetString("Status_TBRError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar representators map loaded successfully from path.
        /// </summary>
        internal static string Status_TBRLoadedSuccessAt {
            get {
                return ResourceManager.GetString("Status_TBRLoadedSuccessAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbars map applyed successfully..
        /// </summary>
        internal static string Status_TBRMapApplyed {
            get {
                return ResourceManager.GetString("Status_TBRMapApplyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar representators map saved successfully at path.
        /// </summary>
        internal static string Status_TBRSavedAt {
            get {
                return ResourceManager.GetString("Status_TBRSavedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab controls loaded successfully from.
        /// </summary>
        internal static string Status_TCCLoadedSuccessAt {
            get {
                return ResourceManager.GetString("Status_TCCLoadedSuccessAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab controls map saved successfully at.
        /// </summary>
        internal static string Status_TCCSavedAt {
            get {
                return ResourceManager.GetString("Status_TCCSavedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC ERROR! Unable to get the resource using key.
        /// </summary>
        internal static string Status_TCError1 {
            get {
                return ResourceManager.GetString("Status_TCError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command cannot be found.
        /// </summary>
        internal static string Status_TheCommandCannotBeFound {
            get {
                return ResourceManager.GetString("Status_TheCommandCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command combination cannot be found.
        /// </summary>
        internal static string Status_TheCommandCombinationCannotBeFound {
            get {
                return ResourceManager.GetString("Status_TheCommandCombinationCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is damaged or not menu items map file..
        /// </summary>
        internal static string Status_TheFileIsDamagedOrNotMIR {
            get {
                return ResourceManager.GetString("Status_TheFileIsDamagedOrNotMIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme file loaded successfully from file.
        /// </summary>
        internal static string Status_ThemeLoadedSuccessfullyFromFile {
            get {
                return ResourceManager.GetString("Status_ThemeLoadedSuccessfullyFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the theme file.
        /// </summary>
        internal static string Status_THMError1 {
            get {
                return ResourceManager.GetString("Status_THMError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is damaged or not a theme file..
        /// </summary>
        internal static string Status_THMError2 {
            get {
                return ResourceManager.GetString("Status_THMError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save the theme file.
        /// </summary>
        internal static string Status_THMError3 {
            get {
                return ResourceManager.GetString("Status_THMError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme file saved successfully at file.
        /// </summary>
        internal static string Status_THMSavedSuccess {
            get {
                return ResourceManager.GetString("Status_THMSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total of.
        /// </summary>
        internal static string Status_TotalOf {
            get {
                return ResourceManager.GetString("Status_TotalOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute the command.
        /// </summary>
        internal static string Status_UnableToExecuteCommand {
            get {
                return ResourceManager.GetString("Status_UnableToExecuteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the menu items map.
        /// </summary>
        internal static string Status_UnableToLoadMIRMap {
            get {
                return ResourceManager.GetString("Status_UnableToLoadMIRMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the toolbar representators map.
        /// </summary>
        internal static string Status_UnableToLoadTBRMapFile {
            get {
                return ResourceManager.GetString("Status_UnableToLoadTBRMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the tab controls map.
        /// </summary>
        internal static string Status_UnableToLoadTCCMapFile {
            get {
                return ResourceManager.GetString("Status_UnableToLoadTCCMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the map file.
        /// </summary>
        internal static string Status_UnableToLoadTheMapFile {
            get {
                return ResourceManager.GetString("Status_UnableToLoadTheMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the shortcuts map.
        /// </summary>
        internal static string Status_UnableToLoadTheShortcutsMap {
            get {
                return ResourceManager.GetString("Status_UnableToLoadTheShortcutsMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save the map file.
        /// </summary>
        internal static string Status_UnableToSaveTheMapFile {
            get {
                return ResourceManager.GetString("Status_UnableToSaveTheMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string TC_Name_Log {
            get {
                return ResourceManager.GetString("TC_Name_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Settings.
        /// </summary>
        internal static string Title_ExportSettings {
            get {
                return ResourceManager.GetString("Title_ExportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Settings.
        /// </summary>
        internal static string Title_ImportSettings {
            get {
                return ResourceManager.GetString("Title_ImportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Items Map Editor.
        /// </summary>
        internal static string Title_MIREditor {
            get {
                return ResourceManager.GetString("Title_MIREditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Menu Items Map file.
        /// </summary>
        internal static string Title_OpenMenuItemsMapFile {
            get {
                return ResourceManager.GetString("Title_OpenMenuItemsMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Shortcuts Map file.
        /// </summary>
        internal static string Title_OpenShortcutsMapFile {
            get {
                return ResourceManager.GetString("Title_OpenShortcutsMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open controls layout file.
        /// </summary>
        internal static string Title_OpenTabsControlsLayout {
            get {
                return ResourceManager.GetString("Title_OpenTabsControlsLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Theme File.
        /// </summary>
        internal static string Title_OpenThemeFile {
            get {
                return ResourceManager.GetString("Title_OpenThemeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Toolbars Map file.
        /// </summary>
        internal static string Title_OpenToolbarsMapFile {
            get {
                return ResourceManager.GetString("Title_OpenToolbarsMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save log into file.
        /// </summary>
        internal static string Title_SaveLogIntoFile {
            get {
                return ResourceManager.GetString("Title_SaveLogIntoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Menu Items Map file.
        /// </summary>
        internal static string Title_SaveMenuItemsMapFile {
            get {
                return ResourceManager.GetString("Title_SaveMenuItemsMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Shortcuts Map file.
        /// </summary>
        internal static string Title_SaveShortcutsMapFile {
            get {
                return ResourceManager.GetString("Title_SaveShortcutsMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save controls layout into file.
        /// </summary>
        internal static string Title_SaveTabsControlsLayout {
            get {
                return ResourceManager.GetString("Title_SaveTabsControlsLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Theme To File.
        /// </summary>
        internal static string Title_SaveThemeFile {
            get {
                return ResourceManager.GetString("Title_SaveThemeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Toolbars Map file.
        /// </summary>
        internal static string Title_SaveToolbarsMapFile {
            get {
                return ResourceManager.GetString("Title_SaveToolbarsMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts (Hotkeys) Map Editor.
        /// </summary>
        internal static string Title_ShortcutsMapEditor {
            get {
                return ResourceManager.GetString("Title_ShortcutsMapEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Editor.
        /// </summary>
        internal static string Title_ThemeEditor {
            get {
                return ResourceManager.GetString("Title_ThemeEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbars Map Editor.
        /// </summary>
        internal static string Title_ToolbarsMapEditor {
            get {
                return ResourceManager.GetString("Title_ToolbarsMapEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank Textbox.
        /// </summary>
        internal static string TMI_Name_BlankTMI {
            get {
                return ResourceManager.GetString("TMI_Name_BlankTMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a blank textbox for testing purpose.
        /// </summary>
        internal static string TMI_Tooltip_BlankTMI {
            get {
                return ResourceManager.GetString("TMI_Tooltip_BlankTMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel in.
        /// </summary>
        internal static string Word_CancelIn {
            get {
                return ResourceManager.GetString("Word_CancelIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        internal static string Word_Command {
            get {
                return ResourceManager.GetString("Word_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file for details.
        /// </summary>
        internal static string Word_FileForDetails {
            get {
                return ResourceManager.GetString("Word_FileForDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string Word_Main {
            get {
                return ResourceManager.GetString("Word_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu item.
        /// </summary>
        internal static string Word_MenuItem {
            get {
                return ResourceManager.GetString("Word_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing service id.
        /// </summary>
        internal static string Word_MissingServiceID {
            get {
                return ResourceManager.GetString("Word_MissingServiceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Toolsbar.
        /// </summary>
        internal static string Word_NewToolsbar {
            get {
                return ResourceManager.GetString("Word_NewToolsbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Word_No {
            get {
                return ResourceManager.GetString("Word_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please see.
        /// </summary>
        internal static string Word_PleaseSee {
            get {
                return ResourceManager.GetString("Word_PleaseSee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press key(s) for.
        /// </summary>
        internal static string Word_PressKeysFor {
            get {
                return ResourceManager.GetString("Word_PressKeysFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second(s).
        /// </summary>
        internal static string Word_Seconds {
            get {
                return ResourceManager.GetString("Word_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service with id.
        /// </summary>
        internal static string Word_ServiceWithID {
            get {
                return ResourceManager.GetString("Word_ServiceWithID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitter.
        /// </summary>
        internal static string Word_Splitter {
            get {
                return ResourceManager.GetString("Word_Splitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Word_Yes {
            get {
                return ResourceManager.GetString("Word_Yes", resourceCulture);
            }
        }
    }
}
